/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CouponType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Coupon details
 */
@Schema(description = "Coupon details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-10-07T11:58:45.449444800+03:00[Asia/Jerusalem]")public class CouponDetails {

  @SerializedName("title")
  private String title = null;

  @SerializedName("couponType")
  private CouponType couponType = null;

  @SerializedName("amount")
  private Integer amount = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("price")
  private Integer price = null;

  @SerializedName("startDate")
  private String startDate = null;

  @SerializedName("expiryDate")
  private String expiryDate = null;

  @SerializedName("image")
  private String image = null;
  public CouponDetails title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * Get title
  * @return title
  **/
  @Schema(example = "Vacation voucher", description = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public CouponDetails couponType(CouponType couponType) {
    this.couponType = couponType;
    return this;
  }

  

  /**
  * Get couponType
  * @return couponType
  **/
  @Schema(description = "")
  public CouponType getCouponType() {
    return couponType;
  }
  public void setCouponType(CouponType couponType) {
    this.couponType = couponType;
  }
  public CouponDetails amount(Integer amount) {
    this.amount = amount;
    return this;
  }

  

  /**
  * Get amount
  * @return amount
  **/
  @Schema(example = "50", description = "")
  public Integer getAmount() {
    return amount;
  }
  public void setAmount(Integer amount) {
    this.amount = amount;
  }
  public CouponDetails description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  @Schema(example = "10% discount on the best vacation for you!", description = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public CouponDetails price(Integer price) {
    this.price = price;
    return this;
  }

  

  /**
  * Get price
  * @return price
  **/
  @Schema(example = "100", description = "")
  public Integer getPrice() {
    return price;
  }
  public void setPrice(Integer price) {
    this.price = price;
  }
  public CouponDetails startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

  

  /**
  * Get startDate
  * @return startDate
  **/
  @Schema(example = "2019-05-17", description = "")
  public String getStartDate() {
    return startDate;
  }
  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }
  public CouponDetails expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

  

  /**
  * Get expiryDate
  * @return expiryDate
  **/
  @Schema(example = "2019-05-17", description = "")
  public String getExpiryDate() {
    return expiryDate;
  }
  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }
  public CouponDetails image(String image) {
    this.image = image;
    return this;
  }

  

  /**
  * Get image
  * @return image
  **/
  @Schema(example = "www.image.com", description = "")
  public String getImage() {
    return image;
  }
  public void setImage(String image) {
    this.image = image;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponDetails couponDetails = (CouponDetails) o;
    return Objects.equals(this.title, couponDetails.title) &&
        Objects.equals(this.couponType, couponDetails.couponType) &&
        Objects.equals(this.amount, couponDetails.amount) &&
        Objects.equals(this.description, couponDetails.description) &&
        Objects.equals(this.price, couponDetails.price) &&
        Objects.equals(this.startDate, couponDetails.startDate) &&
        Objects.equals(this.expiryDate, couponDetails.expiryDate) &&
        Objects.equals(this.image, couponDetails.image);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(title, couponType, amount, description, price, startDate, expiryDate, image);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponDetails {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    couponType: ").append(toIndentedString(couponType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
