/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CompaniesList;
import io.swagger.client.model.CompanyDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminFunctionalityCompaniesApi
 */
@Ignore
public class AdminFunctionalityCompaniesApiTest {

    private final AdminFunctionalityCompaniesApi api = new AdminFunctionalityCompaniesApi();

    /**
     * Create a new company in the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminCreateCompanyTest() throws ApiException {
        CompanyDetails body = null;
        String response = api.adminCreateCompany(body);

        // TODO: test validations
    }
    /**
     * get the details of all the companies registered in the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCompaniesTest() throws ApiException {
        CompaniesList response = api.getAllCompanies();

        // TODO: test validations
    }
    /**
     * get company details from the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyAsAdminTest() throws ApiException {
        Integer couponId = null;
        CompanyDetails response = api.getCompanyAsAdmin(couponId);

        // TODO: test validations
    }
    /**
     * Remove exsiting company from the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeComapnyTest() throws ApiException {
        Integer companyId = null;
        String response = api.removeComapny(companyId);

        // TODO: test validations
    }
    /**
     * Update exsiting company details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateComapnyTest() throws ApiException {
        Integer companyId = null;
        CompanyDetails body = null;
        String response = api.updateComapny(companyId, body);

        // TODO: test validations
    }
}
