/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ClientLoginDetails;
import io.swagger.client.model.ClientSigningDetails;
import io.swagger.client.model.CustomerDetails;
import io.swagger.client.model.CustomersList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminFunctionalityCustomersApi
 */
@Ignore
public class AdminFunctionalityCustomersApiTest {

    private final AdminFunctionalityCustomersApi api = new AdminFunctionalityCustomersApi();

    /**
     * Create a new customer in the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void adminCreateCustomerTest() throws ApiException {
        ClientSigningDetails body = null;
        String response = api.adminCreateCustomer(body);

        // TODO: test validations
    }
    /**
     * get all the Customers registered in the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCustomersTest() throws ApiException {
        CustomersList response = api.getAllCustomers();

        // TODO: test validations
    }
    /**
     * get a Customer details from the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerAsAdminTest() throws ApiException {
        Integer customerId = null;
        CustomerDetails response = api.getCustomerAsAdmin(customerId);

        // TODO: test validations
    }
    /**
     * Remove exsiting customer from the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeCustomerTest() throws ApiException {
        Integer customerId = null;
        String response = api.removeCustomer(customerId);

        // TODO: test validations
    }
    /**
     * Update exsiting cutomer details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCustomerTest() throws ApiException {
        Integer customerId = null;
        ClientLoginDetails body = null;
        String response = api.updateCustomer(customerId, body);

        // TODO: test validations
    }
}
