/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CouponDetails;
import io.swagger.client.model.CouponsList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminFunctionalityCouponsApi
 */
@Ignore
public class AdminFunctionalityCouponsApiTest {

    private final AdminFunctionalityCouponsApi api = new AdminFunctionalityCouponsApi();

    /**
     * Create a new Coupon in the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCouponTest() throws ApiException {
        CouponDetails body = null;
        String response = api.createCoupon(body);

        // TODO: test validations
    }
    /**
     * get the Coupons registered in the coupon system by companyId.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCouponsTest() throws ApiException {
        Integer companyId = null;
        CouponsList response = api.getAllCoupons(companyId);

        // TODO: test validations
    }
    /**
     * get a Coupon details from the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCouponDetailsAsAdminTest() throws ApiException {
        Integer couponId = null;
        CouponDetails response = api.getCouponDetailsAsAdmin(couponId);

        // TODO: test validations
    }
    /**
     * Remove exsiting Coupon from the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeCouponTest() throws ApiException {
        Integer couponId = null;
        String response = api.removeCoupon(couponId);

        // TODO: test validations
    }
    /**
     * Update exsiting Coupon details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCouponAsAdminTest() throws ApiException {
        Integer couponId = null;
        CouponDetails body = null;
        String response = api.updateCouponAsAdmin(couponId, body);

        // TODO: test validations
    }
}
