/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CouponDetails;
import io.swagger.client.model.CouponsList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CompanyFunctionalityApi
 */
@Ignore
public class CompanyFunctionalityApiTest {

    private final CompanyFunctionalityApi api = new CompanyFunctionalityApi();

    /**
     * Create a new company coupon in the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCompanyCouponTest() throws ApiException {
        CouponDetails body = null;
        String response = api.createCompanyCoupon(body);

        // TODO: test validations
    }
    /**
     * get a Coupon details from the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyCouponTest() throws ApiException {
        Integer couponId = null;
        CouponDetails response = api.getCompanyCoupon(couponId);

        // TODO: test validations
    }
    /**
     * get the company coupons.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCompanyCouponsTest() throws ApiException {
        CouponsList response = api.getCompanyCoupons();

        // TODO: test validations
    }
    /**
     * Remove exsiting company coupon from the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeCompanyCouponTest() throws ApiException {
        Integer couponId = null;
        String response = api.removeCompanyCoupon(couponId);

        // TODO: test validations
    }
    /**
     * Update exsiting Coupon details
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCouponTest() throws ApiException {
        Integer couponId = null;
        CouponDetails body = null;
        String response = api.updateCoupon(couponId, body);

        // TODO: test validations
    }
}
