/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CouponType;
import io.swagger.client.model.CouponsList;
import io.swagger.client.model.CustomerDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerFunctionalityApi
 */
@Ignore
public class CustomerFunctionalityApiTest {

    private final CustomerFunctionalityApi api = new CustomerFunctionalityApi();

    /**
     * get the available coupons for the client in the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAvailableCouponsTest() throws ApiException {
        Integer customerId = null;
        CouponsList couponType = null;
        Integer price = null;
        CouponType response = api.getAvailableCoupons(customerId, couponType, price);

        // TODO: test validations
    }
    /**
     * get the Coupons registered in the coupon system by customerId.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerCouponsTest() throws ApiException {
        Integer customerId = null;
        CouponsList response = api.getCustomerCoupons(customerId);

        // TODO: test validations
    }
    /**
     * get a Customer details from the coupon system.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCustomerDetailsTest() throws ApiException {
        Integer customerId = null;
        CustomerDetails response = api.getCustomerDetails(customerId);

        // TODO: test validations
    }
}
