/*
 * YossiF93 - Coupons System (Server Side)
 * CRUD APIs for mangaging the Coupon System .
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ClientSigningDetails;
import io.swagger.client.model.CompanyDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SigningApiApi
 */
@Ignore
public class SigningApiApiTest {

    private final SigningApiApi api = new SigningApiApi();

    /**
     * Sign in as a new member to the Coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clientSigningTest() throws ApiException {
        ClientSigningDetails body = null;
        String response = api.clientSigning(body);

        // TODO: test validations
    }
    /**
     * Create a new company in the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCompanyTest() throws ApiException {
        CompanyDetails body = null;
        String response = api.createCompany(body);

        // TODO: test validations
    }
    /**
     * Create a new customer in the coupon system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCustomerTest() throws ApiException {
        ClientSigningDetails body = null;
        String response = api.createCustomer(body);

        // TODO: test validations
    }
}
